# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/dff.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/clock_generate.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/buffer_2.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/buffer.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/clock_generator_1k.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/singlepulse.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/pitch_shifting.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/clock_generator_20.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/songs.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/amplify_songs.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/speaker_mic_led.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/Seven_segment_LED_Display_Controller.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/pitch_option.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/one_second_delay.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/loudness.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/button.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/SPI.v}
  {C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/new/AUDIO_FX_TOP.v}
}
read_vhdl -library xil_defaultlib {{C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/sources_1/imports/audio_effects.srcs/DA2CompRef.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/constrs_1/imports/Learn/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Sharon Chiang/Desktop/audio_effects_combined/audio_effects.srcs/constrs_1/imports/Learn/Basys3_Master.xdc}}]


synth_design -top AUDIO_FX_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef AUDIO_FX_TOP.dcp

catch { report_utilization -file AUDIO_FX_TOP_utilization_synth.rpt -pb AUDIO_FX_TOP_utilization_synth.pb }
